package ua.goit.goitnotes.validation;

public enum ValidationError {
    WRONG_NOTE_TITLE_LENGTH,
    WRONG_NOTE_CONTENT_LENGTH,
    WRONG_USER_NAME_LENGTH,
    WRONG_USER_NAME_SYMBOLS,
    WRONG_ACCESS_TYPE,
    WRONG_USER_PASSWORD_LENGTH,
    NOTE_TITLE_NOT_UNIQUE_FOR_CURRENT_USER,
    USER_NAME_NOT_UNIQUE
}
